require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AboutAasController do

  # This should return the minimal set of attributes required to create a valid
  # AboutAa. As you add validations to AboutAa, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all about_aas as @about_aas" do
      about_aa = AboutAa.create! valid_attributes
      get :index
      assigns(:about_aas).should eq([about_aa])
    end
  end

  describe "GET show" do
    it "assigns the requested about_aa as @about_aa" do
      about_aa = AboutAa.create! valid_attributes
      get :show, :id => about_aa.id.to_s
      assigns(:about_aa).should eq(about_aa)
    end
  end

  describe "GET new" do
    it "assigns a new about_aa as @about_aa" do
      get :new
      assigns(:about_aa).should be_a_new(AboutAa)
    end
  end

  describe "GET edit" do
    it "assigns the requested about_aa as @about_aa" do
      about_aa = AboutAa.create! valid_attributes
      get :edit, :id => about_aa.id.to_s
      assigns(:about_aa).should eq(about_aa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AboutAa" do
        expect {
          post :create, :about_aa => valid_attributes
        }.to change(AboutAa, :count).by(1)
      end

      it "assigns a newly created about_aa as @about_aa" do
        post :create, :about_aa => valid_attributes
        assigns(:about_aa).should be_a(AboutAa)
        assigns(:about_aa).should be_persisted
      end

      it "redirects to the created about_aa" do
        post :create, :about_aa => valid_attributes
        response.should redirect_to(AboutAa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved about_aa as @about_aa" do
        # Trigger the behavior that occurs when invalid params are submitted
        AboutAa.any_instance.stub(:save).and_return(false)
        post :create, :about_aa => {}
        assigns(:about_aa).should be_a_new(AboutAa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AboutAa.any_instance.stub(:save).and_return(false)
        post :create, :about_aa => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested about_aa" do
        about_aa = AboutAa.create! valid_attributes
        # Assuming there are no other about_aas in the database, this
        # specifies that the AboutAa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AboutAa.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => about_aa.id, :about_aa => {'these' => 'params'}
      end

      it "assigns the requested about_aa as @about_aa" do
        about_aa = AboutAa.create! valid_attributes
        put :update, :id => about_aa.id, :about_aa => valid_attributes
        assigns(:about_aa).should eq(about_aa)
      end

      it "redirects to the about_aa" do
        about_aa = AboutAa.create! valid_attributes
        put :update, :id => about_aa.id, :about_aa => valid_attributes
        response.should redirect_to(about_aa)
      end
    end

    describe "with invalid params" do
      it "assigns the about_aa as @about_aa" do
        about_aa = AboutAa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AboutAa.any_instance.stub(:save).and_return(false)
        put :update, :id => about_aa.id.to_s, :about_aa => {}
        assigns(:about_aa).should eq(about_aa)
      end

      it "re-renders the 'edit' template" do
        about_aa = AboutAa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AboutAa.any_instance.stub(:save).and_return(false)
        put :update, :id => about_aa.id.to_s, :about_aa => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested about_aa" do
      about_aa = AboutAa.create! valid_attributes
      expect {
        delete :destroy, :id => about_aa.id.to_s
      }.to change(AboutAa, :count).by(-1)
    end

    it "redirects to the about_aas list" do
      about_aa = AboutAa.create! valid_attributes
      delete :destroy, :id => about_aa.id.to_s
      response.should redirect_to(about_aas_url)
    end
  end

end
